-- Seed: 20 email templates for AI Email Assistant.
-- Run manually in Supabase SQL Editor (copy and paste).
--
-- Required for ON CONFLICT (naam) DO NOTHING: naam must be unique.
-- If the constraint is missing, run this once before the INSERT:
--
--   ALTER TABLE email_templates ADD CONSTRAINT email_templates_naam_key UNIQUE (naam);
--
-- (Omit if the constraint already exists.)

INSERT INTO email_templates (
  naam,
  categorie,
  actief,
  onderwerp_nl,
  onderwerp_en,
  onderwerp_es,
  onderwerp_ru,
  onderwerp_th,
  onderwerp_de,
  onderwerp_fr,
  inhoud_nl,
  inhoud_en,
  inhoud_es,
  inhoud_ru,
  inhoud_th,
  inhoud_de,
  inhoud_fr
) VALUES
-- 1. Adoptie aanvraag bevestiging
(
  'Adoptie aanvraag bevestiging',
  'adoptie',
  true,
  'We hebben je adoptieaanvraag ontvangen',
  'We have received your adoption application',
  'Hemos recibido tu solicitud de adopción',
  'Мы получили вашу заявку на усыновление',
  'เราได้รับคำขอรับเลี้ยงสัตว์แล้ว',
  'Wir haben Ihre Adoptionsanfrage erhalten',
  'Nous avons bien reçu votre demande d''adoption',
  'Beste {{naam}},\n\nWe hebben je aanvraag ontvangen en nemen zo snel mogelijk contact met je op.\n\nMet vriendelijke groet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe have received your application and will get back to you as soon as possible.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nHemos recibido tu solicitud y nos pondremos en contacto lo antes posible.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nМы получили вашу заявку и свяжемся с вами в ближайшее время.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nเราได้รับคำขอของคุณแล้ว และจะติดต่อกลับโดยเร็ว\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWir haben Ihre Anfrage erhalten und melden uns schnellstmöglich.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous avons bien reçu votre demande et vous recontacterons au plus vite.\n\nCordialement,\nSaved Souls Foundation'
),
-- 2. Adoptie documenten ontvangen
(
  'Adoptie documenten ontvangen',
  'adoptie',
  true,
  'We hebben je documenten ontvangen',
  'We have received your documents',
  'Hemos recibido tus documentos',
  'Мы получили ваши документы',
  'เราได้รับเอกสารของคุณแล้ว',
  'Wir haben Ihre Unterlagen erhalten',
  'Nous avons bien reçu vos documents',
  'Beste {{naam}},\n\nWe hebben je documenten in goede orde ontvangen. We beoordelen ze en nemen contact op.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe have received your documents. We will review them and get in touch.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nHemos recibido tus documentos. Los revisaremos y nos pondremos en contacto.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nМы получили ваши документы. Мы их рассмотрим и свяжемся с вами.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nเราได้รับเอกสารแล้ว จะตรวจและติดต่อกลับ\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWir haben Ihre Unterlagen erhalten und werden sie prüfen.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous avons bien reçu vos documents. Nous les examinons et vous recontacterons.\n\nCordialement,\nSaved Souls Foundation'
),
-- 3. Adoptie match beschikbaar
(
  'Adoptie match beschikbaar',
  'adoptie',
  true,
  'We hebben een match voor je: {{dier}}',
  'We have a match for you: {{dier}}',
  'Tenemos una coincidencia para ti: {{dier}}',
  'У нас есть подходящий питомец для вас: {{dier}}',
  'เรามีตัวที่เหมาะกับคุณ: {{dier}}',
  'Wir haben ein passendes Tier für Sie: {{dier}}',
  'Nous avons un animal qui vous correspond : {{dier}}',
  'Beste {{naam}},\n\nWe hebben een match voor je gevonden: {{dier}}. Neem contact met ons op om de volgende stappen te bespreken.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe have found a match for you: {{dier}}. Please contact us to discuss the next steps.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nTenemos una coincidencia para ti: {{dier}}. Contáctanos para los siguientes pasos.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nМы нашли для вас подходящего питомца: {{dier}}. Свяжитесь с нами для обсуждения следующих шагов.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nเราพบตัวที่เหมาะกับคุณ: {{dier}} กรุณาติดต่อเราเพื่อขั้นตอนถัดไป\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWir haben ein passendes Tier für Sie: {{dier}}. Bitte kontaktieren Sie uns für die nächsten Schritte.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous avons trouvé un animal pour vous : {{dier}}. Contactez-nous pour la suite.\n\nCordialement,\nSaved Souls Foundation'
),
-- 4. Adoptie afronding
(
  'Adoptie afronding',
  'adoptie',
  true,
  'Je adoptie is afgerond',
  'Your adoption is complete',
  'Tu adopción está completada',
  'Ваше усыновление завершено',
  'การรับเลี้ยงสัตว์ของคุณเสร็จสมบูรณ์',
  'Ihre Adoption ist abgeschlossen',
  'Votre adoption est finalisée',
  'Beste {{naam}},\n\nGefeliciteerd! De adoptie van {{dier}} is afgerond. Veel geluk samen.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nCongratulations! The adoption of {{dier}} is complete. Wishing you both happiness.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\n¡Felicidades! La adopción de {{dier}} está completada. Mucha felicidad.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nПоздравляем! Усыновление {{dier}} завершено. Желаем счастья.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nยินดีด้วย! การรับเลี้ยง {{dier}} เสร็จสมบูรณ์ ขอให้มีความสุข\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nHerzlichen Glückwunsch! Die Adoption von {{dier}} ist abgeschlossen.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nFélicitations ! L''adoption de {{dier}} est finalisée. Bonheur à vous deux.\n\nCordialement,\nSaved Souls Foundation'
),
-- 5. Vrijwilliger welkom
(
  'Vrijwilliger welkom',
  'vrijwilliger',
  true,
  'Welkom als vrijwilliger bij Saved Souls Foundation',
  'Welcome as a volunteer at Saved Souls Foundation',
  'Bienvenido como voluntario en Saved Souls Foundation',
  'Добро пожаловать в волонтёры Saved Souls Foundation',
  'ยินดีต้อนรับสู่การเป็นอาสาสมัคร Saved Souls Foundation',
  'Willkommen als Freiwillige/r bei Saved Souls Foundation',
  'Bienvenue comme bénévole à Saved Souls Foundation',
  'Beste {{naam}},\n\nWelkom! We zijn blij dat je je hebt aangemeld als vrijwilliger. We nemen snel contact op.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWelcome! We are glad you signed up as a volunteer. We will contact you soon.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\n¡Bienvenido/a! Nos alegra que te hayas registrado como voluntario. Nos pondremos en contacto pronto.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nДобро пожаловать! Мы рады, что вы подали заявку как волонтёр. Мы скоро свяжемся с вами.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nยินดีต้อนรับ! เราดีใจที่คุณสมัครเป็นอาสาสมัคร เราจะติดต่อเร็วๆ นี้\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWillkommen! Wir freuen uns, dass Sie sich als Freiwillige/r angemeldet haben. Wir melden uns bald.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nBienvenue ! Nous sommes ravis de votre inscription comme bénévole. Nous vous recontacterons bientôt.\n\nCordialement,\nSaved Souls Foundation'
),
-- 6. Vrijwilliger video call bevestiging
(
  'Vrijwilliger video call bevestiging',
  'vrijwilliger',
  true,
  'Bevestiging: video call Saved Souls Foundation',
  'Confirmation: video call Saved Souls Foundation',
  'Confirmación: videollamada Saved Souls Foundation',
  'Подтверждение: видеозвонок Saved Souls Foundation',
  'ยืนยัน: วิดีโอคอล Saved Souls Foundation',
  'Bestätigung: Videoanruf Saved Souls Foundation',
  'Confirmation : appel vidéo Saved Souls Foundation',
  'Beste {{naam}},\n\nHierbij bevestigen we de video call. We sturen je een link en tijd. Tot dan!\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nThis confirms our video call. We will send you a link and time. Talk soon!\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nConfirmamos la videollamada. Te enviaremos enlace y hora. ¡Hasta pronto!\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nПодтверждаем видеозвонок. Мы пришлём ссылку и время. До связи!\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nยืนยันการวิดีโอคอล เราจะส่งลิงก์และเวลาให้\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nHiermit bestätigen wir den Videoanruf. Sie erhalten Link und Uhrzeit. Bis bald!\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous confirmons l''appel vidéo. Nous vous enverrons le lien et l''horaire. À bientôt !\n\nCordialement,\nSaved Souls Foundation'
),
-- 7. Vrijwilliger reis bevestigd
(
  'Vrijwilliger reis bevestigd',
  'vrijwilliger',
  true,
  'Je reis naar Thailand is bevestigd',
  'Your trip to Thailand is confirmed',
  'Tu viaje a Tailandia está confirmado',
  'Ваша поездка в Таиланд подтверждена',
  'การเดินทางไปประเทศไทยของคุณได้รับการยืนยัน',
  'Ihre Reise nach Thailand ist bestätigt',
  'Votre voyage en Thaïlande est confirmé',
  'Beste {{naam}},\n\nJe reis is bevestigd. We kijken ernaar uit je te verwelkomen op onze locatie.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nYour trip is confirmed. We look forward to welcoming you at our location.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nTu viaje está confirmado. Esperamos darte la bienvenida.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nВаша поездка подтверждена. Ждём вас у нас.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nการเดินทางของคุณยืนยันแล้ว เรารอต้อนรับคุณ\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nIhre Reise ist bestätigt. Wir freuen uns auf Sie.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nVotre voyage est confirmé. Nous avons hâte de vous accueillir.\n\nCordialement,\nSaved Souls Foundation'
),
-- 8. Vrijwilliger documenten herinnering
(
  'Vrijwilliger documenten herinnering',
  'vrijwilliger',
  true,
  'Herinnering: documenten voor je reis',
  'Reminder: documents for your trip',
  'Recordatorio: documentos para tu viaje',
  'Напоминание: документы для поездки',
  'แจ้งเตือน: เอกสารสำหรับการเดินทาง',
  'Erinnerung: Unterlagen für Ihre Reise',
  'Rappel : documents pour votre voyage',
  'Beste {{naam}},\n\nGraag nog je reisdocumenten uploaden zodat we alles op tijd kunnen regelen.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nPlease upload your travel documents so we can arrange everything in time.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nPor favor sube tus documentos de viaje para poder organizar todo a tiempo.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nПожалуйста, загрузите документы для поездки.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nกรุณาอัปโหลดเอกสารการเดินทาง\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nBitte laden Sie Ihre Reiseunterlagen hoch.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nVeuillez envoyer vos documents de voyage.\n\nCordialement,\nSaved Souls Foundation'
),
-- 9. Donatie bedankt
(
  'Donatie bedankt',
  'donatie',
  true,
  'Dank je wel voor je donatie',
  'Thank you for your donation',
  'Gracias por tu donación',
  'Спасибо за ваше пожертвование',
  'ขอบคุณสำหรับการบริจาค',
  'Vielen Dank für Ihre Spende',
  'Merci pour votre don',
  'Beste {{naam}},\n\nHartelijk dank voor je donatie aan {{organisatie}}. Elke bijdrage helpt onze dieren.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nThank you for your donation to {{organisatie}}. Every contribution helps our animals.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nGracias por tu donación a {{organisatie}}. Cada aporte ayuda a nuestros animales.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nСпасибо за пожертвование в {{organisatie}}. Каждый вклад помогает нашим животным.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nขอบคุณสำหรับการบริจาคให้ {{organisatie}}\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nVielen Dank für Ihre Spende an {{organisatie}}.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nMerci pour votre don à {{organisatie}}. Chaque don compte.\n\nCordialement,\nSaved Souls Foundation'
),
-- 10. Donatie maandelijkse bevestiging
(
  'Donatie maandelijkse bevestiging',
  'donatie',
  true,
  'Bevestiging maandelijkse donatie',
  'Monthly donation confirmation',
  'Confirmación de donación mensual',
  'Подтверждение ежемесячного пожертвования',
  'ยืนยันการบริจาครายเดือน',
  'Bestätigung monatliche Spende',
  'Confirmation don mensuel',
  'Beste {{naam}},\n\nWe bevestigen je maandelijkse donatie. Bedankt voor je voortdurende steun.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe confirm your monthly donation. Thank you for your ongoing support.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nConfirmamos tu donación mensual. Gracias por tu apoyo continuo.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nПодтверждаем ваше ежемесячное пожертвование. Спасибо за поддержку.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nยืนยันการบริจาครายเดือนของคุณ ขอบคุณที่สนับสนุนอย่างต่อเนื่อง\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWir bestätigen Ihre monatliche Spende. Danke für Ihre Unterstützung.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous confirmons votre don mensuel. Merci pour votre soutien.\n\nCordialement,\nSaved Souls Foundation'
),
-- 11. Donatie herinnering
(
  'Donatie herinnering',
  'donatie',
  true,
  'Herinnering: steun onze dieren',
  'Reminder: support our animals',
  'Recordatorio: apoya a nuestros animales',
  'Напоминание: поддержите наших животных',
  'แจ้งเตือน: ร่วมสนับสนุนสัตว์ของเรา',
  'Erinnerung: Unterstützen Sie unsere Tiere',
  'Rappel : soutenez nos animaux',
  'Beste {{naam}},\n\nOnze dieren kunnen nog steeds je steun gebruiken. Elke donatie telt.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nOur animals could still use your support. Every donation counts.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nNuestros animales siguen necesitando tu apoyo. Cada donación cuenta.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nНашим животным по-прежнему нужна ваша поддержка.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nสัตว์ของเรายังต้องการการสนับสนุนจากคุณ\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nUnsere Tiere brauchen weiterhin Ihre Unterstützung.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNos animaux ont encore besoin de votre soutien.\n\nCordialement,\nSaved Souls Foundation'
),
-- 12. Sponsor welkom
(
  'Sponsor welkom',
  'sponsor',
  true,
  'Welkom als sponsor van {{dier}}',
  'Welcome as sponsor of {{dier}}',
  'Bienvenido como sponsor de {{dier}}',
  'Добро пожаловать как спонсор {{dier}}',
  'ยินดีต้อนรับในฐานะสปอนเซอร์ของ {{dier}}',
  'Willkommen als Sponsor von {{dier}}',
  'Bienvenue comme parrain/marraine de {{dier}}',
  'Beste {{naam}},\n\nWelkom als sponsor! Je ondersteunt {{dier}} met je maandelijkse bijdrage. We sturen je updates.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWelcome as a sponsor! You are supporting {{dier}} with your monthly contribution. We will send you updates.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\n¡Bienvenido como sponsor! Apoyas a {{dier}} con tu aporte mensual. Te enviaremos novedades.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nДобро пожаловать! Вы поддерживаете {{dier}}. Мы пришлём новости.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nยินดีต้อนรับในฐานะสปอนเซอร์ คุณสนับสนุน {{dier}} เราจะส่งข่าวสารให้\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWillkommen als Sponsor! Sie unterstützen {{dier}}. Wir senden Ihnen Updates.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nBienvenue ! Vous parrainez {{dier}}. Nous vous enverrons des nouvelles.\n\nCordialement,\nSaved Souls Foundation'
),
-- 13. Sponsor maandelijkse update
(
  'Sponsor maandelijkse update',
  'sponsor',
  true,
  'Update over {{dier}}',
  'Update about {{dier}}',
  'Actualización sobre {{dier}}',
  'Новости о {{dier}}',
  'ข่าวสารเกี่ยวกับ {{dier}}',
  'Update zu {{dier}}',
  'Nouvelles de {{dier}}',
  'Beste {{naam}},\n\nHier is je maandelijkse update over {{dier}}. Bedankt voor je steun!\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nHere is your monthly update about {{dier}}. Thank you for your support!\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nAquí tienes la actualización mensual sobre {{dier}}. ¡Gracias!\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nВот новости о {{dier}}. Спасибо за поддержку!\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nนี่คือข่าวสารรายเดือนเกี่ยวกับ {{dier}} ขอบคุณที่สนับสนุน\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nHier ist Ihr monatliches Update zu {{dier}}. Danke!\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nVoici des nouvelles de {{dier}}. Merci pour votre soutien !\n\nCordialement,\nSaved Souls Foundation'
),
-- 14. Sponsor contract herinnering
(
  'Sponsor contract herinnering',
  'sponsor',
  true,
  'Herinnering: sponsorcontract vernieuwen',
  'Reminder: renew sponsorship',
  'Recordatorio: renovar patrocinio',
  'Напоминание: продление спонсорства',
  'แจ้งเตือน: продлениеการเป็นสปอนเซอร์',
  'Erinnerung: Sponsorship verlängern',
  'Rappel : renouveler le parrainage',
  'Beste {{naam}},\n\nJe sponsorcontract loopt binnenkort af. Neem contact op als je wilt verlengen.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nYour sponsorship will expire soon. Contact us if you wish to renew.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nTu patrocinio vence pronto. Contáctanos para renovar.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nВаше спонсорство скоро истекает. Свяжитесь с нами для продления.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nการเป็นสปอนเซอร์จะหมดอายุเร็วๆ นี้ ติดต่อเราเพื่อต่ออายุ\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nIhre Patenschaft läuft bald aus. Kontaktieren Sie uns zur Verlängerung.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nVotre parrainage arrive à échéance. Contactez-nous pour renouveler.\n\nCordialement,\nSaved Souls Foundation'
),
-- 15. Contact ontvangen
(
  'Contact ontvangen',
  'algemeen',
  true,
  'We hebben je bericht ontvangen',
  'We have received your message',
  'Hemos recibido tu mensaje',
  'Мы получили ваше сообщение',
  'เราได้รับข้อความของคุณแล้ว',
  'Wir haben Ihre Nachricht erhalten',
  'Nous avons bien reçu votre message',
  'Beste {{naam}},\n\nWe hebben je bericht ontvangen en nemen binnen 48 uur contact op.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe have received your message and will get back to you within 48 hours.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nHemos recibido tu mensaje y te responderemos en 48 horas.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nМы получили ваше сообщение и ответим в течение 48 часов.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nเราได้รับข้อความแล้ว จะติดต่อกลับภายใน 48 ชั่วโมง\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWir haben Ihre Nachricht erhalten und melden uns innerhalb von 48 Stunden.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous avons bien reçu votre message et vous recontacterons sous 48 h.\n\nCordialement,\nSaved Souls Foundation'
),
-- 16. Contact antwoord
(
  'Contact antwoord',
  'algemeen',
  true,
  'Antwoord op je vraag',
  'Reply to your question',
  'Respuesta a tu consulta',
  'Ответ на ваш вопрос',
  'คำตอบสำหรับคำถามของคุณ',
  'Antwort auf Ihre Anfrage',
  'Réponse à votre question',
  'Beste {{naam}},\n\nHierbij ons antwoord op je vraag. Laat het weten als je nog iets nodig hebt.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nPlease find our reply to your question. Let us know if you need anything else.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nAquí está nuestra respuesta. Avísanos si necesitas algo más.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nВот наш ответ. Напишите, если нужна ещё помощь.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nนี่คือคำตอบของเรา แจ้งได้หากต้องการความช่วยเหลือเพิ่ม\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nHier ist unsere Antwort. Melden Sie sich bei weiteren Fragen.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nVoici notre réponse. N''hésitez pas à nous recontacter.\n\nCordialement,\nSaved Souls Foundation'
),
-- 17. Algemeen nieuws
(
  'Algemeen nieuws',
  'algemeen',
  true,
  'Nieuws van Saved Souls Foundation',
  'News from Saved Souls Foundation',
  'Noticias de Saved Souls Foundation',
  'Новости Saved Souls Foundation',
  'ข่าวสารจาก Saved Souls Foundation',
  'Neuigkeiten von Saved Souls Foundation',
  'Nouvelles de Saved Souls Foundation',
  'Beste {{naam}},\n\nGraag delen we het laatste nieuws van {{organisatie}}. Lees meer in deze e-mail.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe would like to share the latest news from {{organisatie}}. Read more in this email.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nCompartimos las últimas noticias de {{organisatie}}.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nНовости от {{organisatie}}.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nข่าวสารล่าสุดจาก {{organisatie}}\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nNeuigkeiten von {{organisatie}}.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNouvelles de {{organisatie}}.\n\nCordialement,\nSaved Souls Foundation'
),
-- 18. Vrijwilliger aanmelding bevestiging
(
  'Vrijwilliger aanmelding bevestiging',
  'vrijwilliger',
  true,
  'Aanmelding vrijwilliger ontvangen',
  'Volunteer registration received',
  'Registro de voluntario recibido',
  'Заявка волонтёра получена',
  'รับการลงทะเบียนอาสาสมัครแล้ว',
  'Freiwilligen-Anmeldung erhalten',
  'Inscription bénévole reçue',
  'Beste {{naam}},\n\nWe hebben je aanmelding als vrijwilliger ontvangen. We nemen contact op voor de volgende stap.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nWe have received your volunteer registration. We will contact you for the next step.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nHemos recibido tu registro como voluntario. Te contactaremos para el siguiente paso.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nМы получили вашу заявку. Свяжемся с вами для следующего шага.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nเราได้รับการลงทะเบียนอาสาสมัครแล้ว จะติดต่อเพื่อขั้นตอนถัดไป\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nWir haben Ihre Anmeldung erhalten. Wir melden uns für den nächsten Schritt.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nNous avons bien reçu votre inscription. Nous vous recontacterons pour la suite.\n\nCordialement,\nSaved Souls Foundation'
),
-- 19. Adoptie vraag beantwoord
(
  'Adoptie vraag beantwoord',
  'adoptie',
  true,
  'Antwoord op je adoptievraag',
  'Answer to your adoption question',
  'Respuesta a tu pregunta de adopción',
  'Ответ на ваш вопрос об усыновлении',
  'คำตอบสำหรับคำถามการรับเลี้ยง',
  'Antwort auf Ihre Adoptionsfrage',
  'Réponse à votre question d''adoption',
  'Beste {{naam}},\n\nHierbij het antwoord op je vraag over adoptie. Laat het weten als je meer wilt weten.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nHere is the answer to your adoption question. Let us know if you need more information.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nAquí está la respuesta a tu pregunta sobre adopción.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nВот ответ на ваш вопрос об усыновлении.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nนี่คือคำตอบสำหรับคำถามเกี่ยวกับการรับเลี้ยง\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nHier ist die Antwort auf Ihre Adoptionsfrage.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nVoici la réponse à votre question sur l''adoption.\n\nCordialement,\nSaved Souls Foundation'
),
-- 20. Donatie jaaroverzicht
(
  'Donatie jaaroverzicht',
  'donatie',
  true,
  'Je jaaroverzicht 2024 – Saved Souls Foundation',
  'Your 2024 year summary – Saved Souls Foundation',
  'Tu resumen del año 2024 – Saved Souls Foundation',
  'Ваш итог 2024 года – Saved Souls Foundation',
  'สรุปประจำปี 2024 ของคุณ – Saved Souls Foundation',
  'Ihr Jahresrückblick 2024 – Saved Souls Foundation',
  'Votre récapitulatif 2024 – Saved Souls Foundation',
  'Beste {{naam}},\n\nBedankt voor je steun in 2024. Hier is een kort overzicht van wat we samen hebben bereikt.\n\nGroet,\nSaved Souls Foundation',
  'Dear {{naam}},\n\nThank you for your support in 2024. Here is a short summary of what we achieved together.\n\nKind regards,\nSaved Souls Foundation',
  'Estimado/a {{naam}},\n\nGracias por tu apoyo en 2024. Aquí un resumen de lo logrado.\n\nSaludos,\nSaved Souls Foundation',
  'Уважаемый/ая {{naam}},\n\nСпасибо за поддержку в 2024. Краткий итог года.\n\nС уважением,\nSaved Souls Foundation',
  'เรียน {{naam}},\n\nขอบคุณที่สนับสนุนในปี 2024 นี่คือสรุปสั้นๆ\n\nด้วยความเคารพ,\nSaved Souls Foundation',
  'Sehr geehrte/r {{naam}},\n\nDanke für Ihre Unterstützung 2024. Hier eine kurze Zusammenfassung.\n\nMit freundlichen Grüßen,\nSaved Souls Foundation',
  'Cher/Chère {{naam}},\n\nMerci pour votre soutien en 2024. Voici un récapitulatif.\n\nCordialement,\nSaved Souls Foundation'
)
ON CONFLICT (naam) DO NOTHING;
