/**
 * Search index for client-side site search.
 * path + labelKey + optional keywords (NL/EN/DE) voor zoeken in inhoud.
 */
export type SearchEntry = { path: string; labelKey: string; keywords?: string };

export const SEARCH_INDEX: SearchEntry[] = [
  { path: "/", labelKey: "home", keywords: "homepage start" },
  { path: "/about-us", labelKey: "aboutUs", keywords: "over ons werk stichting" },
  { path: "/story", labelKey: "ourStory", keywords: "verhaal geschiedenis" },
  { path: "/contact", labelKey: "contact", keywords: "contact email adres" },
  { path: "/get-involved", labelKey: "getInvolved", keywords: "doe mee helpen vrijwilliger" },
  { path: "/gidsen", labelKey: "gidsen", keywords: "gidsen informatie artikelen" },
  { path: "/donate", labelKey: "donate", keywords: "doneren donatie geven steun" },
  { path: "/support", labelKey: "donate", keywords: "steun doneren" },
  { path: "/donate/causes", labelKey: "donateCauses", keywords: "doelen specifiek" },
  { path: "/donate/thai", labelKey: "donate", keywords: "thai bank overschrijving" },
  { path: "/sponsor", labelKey: "sponsor", keywords: "sponsor maandelijks hond" },
  { path: "/volunteer", labelKey: "volunteer", keywords: "vrijwilliger thailand helpen" },
  { path: "/adopt", labelKey: "adopt", keywords: "adopteren hond kat pup" },
  { path: "/shelters", labelKey: "shelters", keywords: "asielen opvang" },
  { path: "/partners", labelKey: "partners", keywords: "partners samenwerking" },
  { path: "/gallery", labelKey: "gallery", keywords: "foto's galerij" },
  { path: "/press", labelKey: "press", keywords: "pers media" },
  { path: "/shop", labelKey: "shop", keywords: "shop winkel" },
  { path: "/faq", labelKey: "faq", keywords: "vragen veelgesteld" },
  { path: "/blog", labelKey: "blog", keywords: "blog nieuws" },
  { path: "/financial-overview", labelKey: "financialOverview", keywords: "financiën jaarverslag" },
  { path: "/school-project", labelKey: "schoolProject", keywords: "school onderwijs" },
  { path: "/feed-a-year", labelKey: "donate", keywords: "voer jaar" },
  { path: "/clinic-renovation", labelKey: "donate", keywords: "kliniek renovatie" },
  { path: "/luchtbrug", labelKey: "adopt", keywords: "luchtbrug adoptie thailand" },
  { path: "/fireworks-pets", labelKey: "fireworksPets", keywords: "vuurwerk oud en nieuw angst" },
  { path: "/nutrition", labelKey: "nutrition", keywords: "voeding voer hondenvoer kattenvoer eten dieet barf" },
  { path: "/health", labelKey: "health", keywords: "gezondheid ziek vaccinatie" },
  { path: "/flea-tick-parasite-guide", labelKey: "fleaTickParasiteGuide", keywords: "vlooien teken parasieten ontwormen" },
  { path: "/toxic-plants", labelKey: "toxicPlants", keywords: "giftige planten vergiftiging" },
  { path: "/pet-loss", labelKey: "petLoss", keywords: "rouw overlijden verlies huisdier" },
  { path: "/pet-insurance", labelKey: "petInsurance", keywords: "verzekering huisdier" },
  { path: "/senior-pet", labelKey: "seniorPet", keywords: "oude hond senior bejaard" },
  { path: "/microchipping", labelKey: "microchipping", keywords: "chip chippen" },
  { path: "/sterilization", labelKey: "sterilization", keywords: "sterilisatie castratie" },
  { path: "/pet-proof-house", labelKey: "petProofHouse", keywords: "huis veilig" },
  { path: "/pet-sitter", labelKey: "petSitter", keywords: "oppas oppassen" },
  { path: "/pet-passport", labelKey: "petPassport", keywords: "paspoort reizen" },
  { path: "/pet-and-children", labelKey: "petAndChildren", keywords: "kinderen baby" },
  { path: "/overheating", labelKey: "overheating", keywords: "oververhitting warmte hitte" },
  { path: "/foster", labelKey: "foster", keywords: "pleeggezin pleeg" },
  { path: "/behavior", labelKey: "behavior", keywords: "gedrag probleem blaffen" },
  { path: "/toys-training", labelKey: "toysTraining", keywords: "speelgoed training" },
  { path: "/raw-hide", labelKey: "rawHide", keywords: "rauwe huid kauwbot" },
  { path: "/dog-home-alone", labelKey: "dogHomeAlone", keywords: "hond alleen thuis" },
  { path: "/walking-dog", labelKey: "walkingDog", keywords: "uitlaten wandelen dagelijkse wandelingen uitlaatbehoefte alleen thuis gewoontes routine" },
  { path: "/travel-with-pet", labelKey: "travelWithPet", keywords: "reizen vakantie" },
  { path: "/house-training", labelKey: "houseTraining", keywords: "zindelijk zindelijkheid" },
  { path: "/moving-with-pet", labelKey: "movingWithPet", keywords: "verhuizen" },
  { path: "/puppy-socialization", labelKey: "puppySocialization", keywords: "puppy socialisatie" },
  { path: "/dog-barking", labelKey: "dogBarking", keywords: "blaffen" },
  { path: "/dog-and-cat-together", labelKey: "dogAndCatTogether", keywords: "hond kat samen" },
  { path: "/cat-hairball", labelKey: "catHairball", keywords: "haarbal kat" },
  { path: "/cat-indoor-outdoor", labelKey: "catIndoorOutdoor", keywords: "kat binnen buiten" },
  { path: "/dog-vomiting-diarrhea", labelKey: "dogVomitingDiarrhea", keywords: "braken diarree" },
  { path: "/disabled-dog-guide", labelKey: "disabledDogGuide", keywords: "gehandicapte hond" },
  { path: "/dog-meat-survivors", labelKey: "dogMeatSurvivors", keywords: "vleestruck vleeshandel" },
  { path: "/paralyzed-dogs-guide", labelKey: "paralyzedDogsGuide", keywords: "rolstoel verlamd rolstoelhond" },
  { path: "/first-aid", labelKey: "health", keywords: "eerste hulp" },
  { path: "/first-aid-at-home", labelKey: "health", keywords: "eerste hulp thuis" },
  { path: "/first-pet-home", labelKey: "adopt", keywords: "eerste huisdier" },
  { path: "/street-dogs-thailand", labelKey: "streetDogsThailand", keywords: "zwerfhonden thailand" },
  { path: "/influencers", labelKey: "influencers", keywords: "influencer social media" },
  { path: "/vet-costs-comparison", labelKey: "vetCostsComparison", keywords: "dierenarts kosten vergelijken" },
  { path: "/william-heinecke-elephants", labelKey: "williamHeineckeElephants", keywords: "olifanten" },
  { path: "/minor-hotels", labelKey: "minorHotels", keywords: "hotel vakantie" },
  { path: "/deworming", labelKey: "deworming", keywords: "ontwormen wormen" },
  { path: "/vaccinations", labelKey: "vaccinations", keywords: "inenten vaccinatie" },
  { path: "/heartworm", labelKey: "heartworm", keywords: "hartworm" },
  { path: "/eye-ear-care", labelKey: "eyeEarCare", keywords: "oor oog" },
  { path: "/dangers", labelKey: "dangers", keywords: "gevaren" },
  { path: "/infections", labelKey: "infections", keywords: "infectie" },
  { path: "/general-health", labelKey: "generalHealth", keywords: "gezondheid algemeen" },
  { path: "/find-out-more", labelKey: "findOutMore", keywords: "meer weten" },
];
