export type SearchPage = {
  path: string;
  title: Record<string, string>;
  description: Record<string, string>;
};

export const SEARCH_INDEX: SearchPage[] = [
  { path: "/faq", title: { nl: "Veelgestelde vragen", en: "FAQ" }, description: { nl: "Antwoorden op veelgestelde vragen over adoptie, sponsoring en de foundation.", en: "Answers to frequently asked questions about adoption, sponsorship and the foundation." } },
  { path: "/health", title: { nl: "Gezondheid", en: "Health" }, description: { nl: "Gezondheidsinformatie voor honden en katten.", en: "Health information for dogs and cats." } },
  { path: "/nutrition", title: { nl: "Voeding", en: "Nutrition" }, description: { nl: "Voedingsadvies voor honden en katten.", en: "Nutrition advice for dogs and cats." } },
  { path: "/behavior", title: { nl: "Gedrag", en: "Behavior" }, description: { nl: "Gedragsproblemen en training voor honden en katten.", en: "Behavior issues and training for dogs and cats." } },
  { path: "/first-aid", title: { nl: "EHBO", en: "First Aid" }, description: { nl: "Eerste hulp bij ongelukken en noodgevallen met huisdieren.", en: "First aid for pet accidents and emergencies." } },
  { path: "/first-aid-at-home", title: { nl: "Eerste hulp thuis", en: "First Aid at Home" }, description: { nl: "Hoe je thuis eerste hulp verleent aan je huisdier.", en: "How to provide first aid to your pet at home." } },
  { path: "/first-pet-home", title: { nl: "Eerste huisdier", en: "First Pet at Home" }, description: { nl: "Alles wat je moet weten als je voor het eerst een huisdier neemt.", en: "Everything you need to know when getting your first pet." } },
  { path: "/flea-tick-parasite-guide", title: { nl: "Vlooien en teken", en: "Fleas and Ticks" }, description: { nl: "Hoe je vlooien teken en parasieten bestrijdt en voorkomt.", en: "How to treat and prevent fleas ticks and parasites." } },
  { path: "/general-health", title: { nl: "Algemene gezondheid", en: "General Health" }, description: { nl: "Algemene gezondheidszorg voor honden en katten.", en: "General healthcare for dogs and cats." } },
  { path: "/vaccinations", title: { nl: "Vaccinaties", en: "Vaccinations" }, description: { nl: "Welke vaccinaties heeft je hond of kat nodig.", en: "Which vaccinations your dog or cat needs." } },
  { path: "/deworming", title: { nl: "Ontwormen", en: "Deworming" }, description: { nl: "Hoe en wanneer je je huisdier ontwormt.", en: "How and when to deworm your pet." } },
  { path: "/heartworm", title: { nl: "Hartworm", en: "Heartworm" }, description: { nl: "Hartworm bij honden en katten preventie en behandeling.", en: "Heartworm in dogs and cats prevention and treatment." } },
  { path: "/eye-ear-care", title: { nl: "Oog en oorverzorging", en: "Eye and Ear Care" }, description: { nl: "Verzorging van ogen en oren bij honden en katten.", en: "Eye and ear care for dogs and cats." } },
  { path: "/ear-mites-sneezing", title: { nl: "Oormijt en niezen", en: "Ear Mites and Sneezing" }, description: { nl: "Oormijt en niesklachten bij huisdieren.", en: "Ear mites and sneezing issues in pets." } },
  { path: "/skin-coat", title: { nl: "Huid en vacht", en: "Skin and Coat" }, description: { nl: "Verzorging van huid en vacht bij honden en katten.", en: "Skin and coat care for dogs and cats." } },
  { path: "/skin-problems", title: { nl: "Huidproblemen", en: "Skin Problems" }, description: { nl: "Veelvoorkomende huidproblemen bij honden en katten.", en: "Common skin problems in dogs and cats." } },
  { path: "/infections", title: { nl: "Infecties", en: "Infections" }, description: { nl: "Infectieziekten bij honden en katten.", en: "Infectious diseases in dogs and cats." } },
  { path: "/tropics", title: { nl: "Tropen", en: "Tropics" }, description: { nl: "Gezondheidsrisicos voor huisdieren in tropische gebieden.", en: "Health risks for pets in tropical areas." } },
  { path: "/dangers", title: { nl: "Gevaren", en: "Dangers" }, description: { nl: "Gevaren en risicos voor huisdieren thuis en buiten.", en: "Dangers and risks for pets at home and outside." } },
  { path: "/cat-flu", title: { nl: "Kattenziekte", en: "Cat Flu" }, description: { nl: "Kattenziekte symptomen behandeling en preventie.", en: "Cat flu symptoms treatment and prevention." } },
  { path: "/dog-vomiting-diarrhea", title: { nl: "Braken en diarree", en: "Vomiting and Diarrhea" }, description: { nl: "Wat te doen als je hond of kat braakt of diarree heeft.", en: "What to do if your dog or cat vomits or has diarrhea." } },
  { path: "/overheating", title: { nl: "Oververhitting", en: "Overheating" }, description: { nl: "Oververhitting bij honden en katten herkennen en handelen.", en: "Overheating in dogs and cats recognizing and acting." } },
  { path: "/microchipping", title: { nl: "Microchip", en: "Microchipping" }, description: { nl: "Waarom en hoe je je huisdier laat chippen.", en: "Why and how to microchip your pet." } },
  { path: "/sterilization", title: { nl: "Sterilisatie", en: "Sterilization" }, description: { nl: "Sterilisatie en castratie van honden en katten.", en: "Sterilization and neutering of dogs and cats." } },
  { path: "/pet-passport", title: { nl: "Dierenpaspoort", en: "Pet Passport" }, description: { nl: "Het dierenpaspoort wat je nodig hebt voor internationale reizen.", en: "The pet passport what you need for international travel." } },
  { path: "/pet-proof-house", title: { nl: "Huisdier veilig huis", en: "Pet Proof House" }, description: { nl: "Hoe je je huis veilig maakt voor een huisdier.", en: "How to make your home safe for a pet." } },
  { path: "/pet-and-children", title: { nl: "Huisdier en kinderen", en: "Pet and Children" }, description: { nl: "Hoe honden en katten samenleven met kinderen.", en: "How dogs and cats live together with children." } },
  { path: "/pet-sitter", title: { nl: "Huisdieroppas", en: "Pet Sitter" }, description: { nl: "Hoe je een goede oppas vindt voor je huisdier.", en: "How to find a good sitter for your pet." } },
  { path: "/pet-insurance", title: { nl: "Huisdierenverzekering", en: "Pet Insurance" }, description: { nl: "Alles over verzekeringen voor honden en katten.", en: "Everything about insurance for dogs and cats." } },
  { path: "/pet-loss", title: { nl: "Verlies huisdier", en: "Pet Loss" }, description: { nl: "Omgaan met het verlies van een huisdier.", en: "Coping with the loss of a pet." } },
  { path: "/senior-pet", title: { nl: "Senior huisdier", en: "Senior Pet" }, description: { nl: "Verzorging van oudere honden en katten.", en: "Care for older dogs and cats." } },
  { path: "/toxic-plants", title: { nl: "Giftige planten", en: "Toxic Plants" }, description: { nl: "Welke planten giftig zijn voor honden en katten.", en: "Which plants are toxic to dogs and cats." } },
  { path: "/foster", title: { nl: "Pleeggezin", en: "Foster" }, description: { nl: "Tijdelijk een hond of kat opvangen als pleeggezin.", en: "Temporarily fostering a dog or cat." } },
  { path: "/dog-home-alone", title: { nl: "Hond alleen thuis", en: "Dog Home Alone" }, description: { nl: "Hoe lang mag een hond alleen thuis zijn en hoe train je dit.", en: "How long can a dog be home alone and how to train this." } },
  { path: "/walking-dog", title: { nl: "Hond uitlaten", en: "Walking Your Dog" }, description: { nl: "Tips voor het uitlaten van je hond.", en: "Tips for walking your dog." } },
  { path: "/travel-with-pet", title: { nl: "Reizen met huisdier", en: "Travel with Pet" }, description: { nl: "Hoe je veilig reist met je hond of kat.", en: "How to travel safely with your dog or cat." } },
  { path: "/house-training", title: { nl: "Zindelijkheidstraining", en: "House Training" }, description: { nl: "Hoe je een hond of kat zindelijk maakt.", en: "How to house train a dog or cat." } },
  { path: "/moving-with-pet", title: { nl: "Verhuizen met huisdier", en: "Moving with Pet" }, description: { nl: "Tips voor verhuizen met een hond of kat.", en: "Tips for moving with a dog or cat." } },
  { path: "/puppy-socialization", title: { nl: "Puppy socialisatie", en: "Puppy Socialization" }, description: { nl: "Hoe je een puppy goed socialiseert.", en: "How to properly socialize a puppy." } },
  { path: "/dog-barking", title: { nl: "Hond blaft", en: "Dog Barking" }, description: { nl: "Waarom honden blaffen en hoe je dit aanpakt.", en: "Why dogs bark and how to address this." } },
  { path: "/cat-indoor-outdoor", title: { nl: "Kat binnen of buiten", en: "Indoor or Outdoor Cat" }, description: { nl: "Binnenkater of buitenkater wat past bij jouw situatie.", en: "Indoor or outdoor cat what suits your situation." } },
  { path: "/cat-hairball", title: { nl: "Haarbal bij katten", en: "Cat Hairball" }, description: { nl: "Haarballen bij katten oorzaak en oplossing.", en: "Hairballs in cats cause and solution." } },
  { path: "/dog-and-cat-together", title: { nl: "Hond en kat samen", en: "Dog and Cat Together" }, description: { nl: "Hoe honden en katten samen kunnen leven.", en: "How dogs and cats can live together." } },
  { path: "/disabled-dog-guide", title: { nl: "Gehandicapte hond", en: "Disabled Dog Guide" }, description: { nl: "Verzorging van gehandicapte en verlamde honden.", en: "Care for disabled and paralyzed dogs." } },
  { path: "/dog-meat-survivors", title: { nl: "Vleeshandel overlevers", en: "Dog Meat Survivors" }, description: { nl: "Honden gered uit de illegale hondenvleeshandel.", en: "Dogs rescued from the illegal dog meat trade." } },
  { path: "/paralyzed-dogs-guide", title: { nl: "Verlamde honden", en: "Paralyzed Dogs" }, description: { nl: "Hoe je zorgt voor een verlamde hond.", en: "How to care for a paralyzed dog." } },
  { path: "/fireworks-pets", title: { nl: "Vuurwerk en huisdieren", en: "Fireworks and Pets" }, description: { nl: "Hoe je je huisdier helpt bij vuurwerk en angst.", en: "How to help your pet during fireworks and fear." } },
  { path: "/street-dogs-thailand", title: { nl: "Zwerfhonden Thailand", en: "Street Dogs Thailand" }, description: { nl: "De situatie van zwerfhonden in Thailand en wat wij doen.", en: "The situation of street dogs in Thailand and what we do." } },
  { path: "/school-project", title: { nl: "Schoolproject", en: "School Project" }, description: { nl: "Educatief schoolproject over dierenwelzijn en Thailand.", en: "Educational school project about animal welfare and Thailand." } },
  { path: "/kids", title: { nl: "Kinderen en dieren", en: "Kids and Animals" }, description: { nl: "Hoe kinderen veilig omgaan met honden en katten.", en: "How children can safely interact with dogs and cats." } },
  { path: "/gidsen", title: { nl: "Gidsen en informatie", en: "Guides and Information" }, description: { nl: "Overzicht van alle gidsen en informatieve artikelen.", en: "Overview of all guides and informative articles." } },
  { path: "/about-us", title: { nl: "Over ons", en: "About Us" }, description: { nl: "Wie we zijn wat we doen en hoe we werken.", en: "Who we are what we do and how we work." } },
  { path: "/story", title: { nl: "Ons verhaal", en: "Our Story" }, description: { nl: "Het verhaal van Saved Souls Foundation vanaf het begin.", en: "The story of Saved Souls Foundation from the beginning." } },
  { path: "/get-involved", title: { nl: "Doe mee", en: "Get Involved" }, description: { nl: "Alle manieren om te helpen doneren sponsoren vrijwilligen.", en: "All ways to help donate sponsor volunteer." } },
  { path: "/volunteer", title: { nl: "Vrijwilliger", en: "Volunteer" }, description: { nl: "Kom vrijwilligerswerk doen in Thailand bij de dieren.", en: "Come volunteer in Thailand with the animals." } },
  { path: "/adopt", title: { nl: "Adopteer", en: "Adopt" }, description: { nl: "Adopteer een hond of kat van Saved Souls Foundation.", en: "Adopt a dog or cat from Saved Souls Foundation." } },
  { path: "/sponsor", title: { nl: "Sponsor een dier", en: "Sponsor an Animal" }, description: { nl: "Sponsor maandelijks een specifieke hond of kat.", en: "Monthly sponsor a specific dog or cat." } },
  { path: "/luchtbrug", title: { nl: "Internationale adoptie", en: "International Adoption" }, description: { nl: "Hoe internationale adoptie werkt Europa USA Canada.", en: "How international adoption works Europe USA Canada." } },
  { path: "/adoptieproces", title: { nl: "Adoptieproces", en: "Adoption Process" }, description: { nl: "Stap voor stap het adoptieproces uitgelegd.", en: "Step by step explanation of the adoption process." } },
  { path: "/soul-saver", title: { nl: "Soul Saver", en: "Soul Saver" }, description: { nl: "Word Soul Saver en help ons structureel.", en: "Become a Soul Saver and help us structurally." } },
  { path: "/raw-hide", title: { nl: "Rawhide", en: "Rawhide" }, description: { nl: "Is rawhide veilig voor honden.", en: "Is rawhide safe for dogs." } },
  { path: "/toys-training", title: { nl: "Speelgoed en training", en: "Toys and Training" }, description: { nl: "Speelgoed en training voor honden en katten.", en: "Toys and training for dogs and cats." } },
  { path: "/financial-overview", title: { nl: "Financieel overzicht", en: "Financial Overview" }, description: { nl: "Transparant overzicht van onze financien.", en: "Transparent overview of our finances." } },
  { path: "/vet-costs-comparison", title: { nl: "Dierenarts kosten", en: "Vet Costs" }, description: { nl: "Vergelijking van dierenartskosten in Thailand.", en: "Comparison of vet costs in Thailand." } },
];
